language: node_js
env: CI=true
node_js:
  - '0.10'
after_script:
  - npm run coveralls
notifications:
  email: false
  slack:
    rooms:
      - generator-m:lZYXd9k3mcYBlsGUnd1xRb3R
    on_success: :change  # options: [always|never|change] default: always
    on_failure: :change  # options: [always|never|change] default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87130ded51c12384d4e7
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
